jobs:
  - name: speedtest
    command: /opt/speedtest2mqtt.sh
    shell: /bin/bash
    schedule1
    env_file: /var/tmp/container.env
    captureStderr: false
    captureStdout: true
    concurrencyPolicy: Forbid

  - name: speedtest_onstart
    command: /opt/speedtest2mqtt.sh
    shell: /bin/bash
    schedule2
    env_file: /var/tmp/container.env
    captureStderr: false
    captureStdout: true
    concurrencyPolicy: Forbid
